language: php

before_script:
  - sudo apt-get update
  - sudo apt-get install -y openoffice.org openoffice.org-writer unoconv
  - composer install --dev --prefer-source

php:
  - 7.0
  - 7.1
  - 7.2

script:
  - phpunit --coverage-text
  - phpunit -c phpunit-functional.xml.dist
